import json, pathlib, collections, hashlib, sys
import numpy as np
sys.path.insert(0, ".")
from sklearn.linear_model import LogisticRegression
from governor.harness.ledger import ExperimentRun, ExperimentSpec
from governor.harness.traps import run_trap_checks, render
from governor.execfeedback.publictests import FEATURE_NAMES

rng = np.random.default_rng(0)
rows = json.loads(pathlib.Path("results/E0026_feedback.json").read_text())
byq = collections.defaultdict(list)
for r in rows: byq[r["qid"]].append(r)
for q in byq: byq[q].sort(key=lambda r: r["sample"])
def is_eval(q): return int(hashlib.sha256(q.encode()).hexdigest(),16)%2==1
cal=sorted(q for q in byq if not is_eval(q)); ev=sorted(q for q in byq if is_eval(q))
F=("pub_frac","pub_passed","pub_failed","runtime_error","timeout","output_nonempty","exec_latency_s")
def fv(r): return [float(r[f]) for f in F]

clf = LogisticRegression(max_iter=2000).fit(
    np.array([fv(byq[q][0]) for q in cal]),
    np.array([1.0 if any(x["graded"] for x in byq[q]) else 0.0 for q in cal]))

def sim(qs, tau):
    U,C,K=[],[],[]
    for q in qs:
        s=byq[q]; tot=0.0; got=0.0; k=0
        for i,r in enumerate(s):
            tot+=r["tokens"]; k=i+1
            if r["graded"]: got=1.0
            if r["pub_all_passed"]: break
            if i==0 and clf.predict_proba([fv(r)])[0,1]<tau: break
        U.append(got); C.append(tot); K.append(k)
    return np.array(U),np.array(C),np.array(K)

def fixed_at(qs,cost):
    cs=[np.mean([sum(r["tokens"] for r in byq[q][:k]) for q in qs]) for k in range(1,11)]
    per=[np.array([1.0 if any(r["graded"] for r in byq[q][:k]) else 0.0 for q in qs]) for k in range(1,11)]
    us=[p.mean() for p in per]
    if cost<=cs[0]: return us[0]*cost/cs[0], per[0]
    for i in range(len(cs)-1):
        if cs[i]<=cost<=cs[i+1]:
            w=(cost-cs[i])/(cs[i+1]-cs[i]); return us[i]+w*(us[i+1]-us[i]), (1-w)*per[i]+w*per[i+1]
    return us[-1], per[-1]

best=None
for tau in np.linspace(0.05,0.95,19):
    U,C,_=sim(cal,tau); ub,_=fixed_at(cal,C.mean())
    if best is None or U.mean()-ub>best[1]: best=(tau,U.mean()-ub)
tau=best[0]
U,C,K=sim(ev,tau); ub,Ub=fixed_at(ev,C.mean())
d=U-Ub
boots=[d[rng.integers(0,len(ev),len(ev))].mean() for _ in range(4000)]
lo,hi=np.percentile(boots,[2.5,97.5])
oracle=np.mean([1.0 if any(r["graded"] for r in byq[q]) else 0.0 for q in ev])
k10=np.mean([sum(r["tokens"] for r in byq[q]) for q in ev])

# --- trap evidence ---
ev_dict = {
 "gov_utils": U, "greedy_utils": Ub, "gov_calls": K, "greedy_calls": np.full(len(K), K.mean()),
 "decisions_by_state": [tuple(np.round(fv(byq[q][0]),3)) for q in ev],
 "feature_names": list(F),
 "answered_rate": 1.0, "utility": float(U.mean()),
 "requested": C, "actual_used": C, "charged": C,
 "scored_via_executor": True,
 "decisions": K.tolist(), "cell_ids": [byq[q][0]["platform"] for q in ev],
 "froze_commit": "b8e2884", "heldout_commit": "HEAD",
 "selection_item_ids": cal, "evaluation_item_ids": ev,
 "token_cost_source": "exact tokenizer count over published LiveCodeBench generations",
 "realised_cost": float(C.mean()), "budget": float(C.mean()),
 "baseline_cost": float(C.mean()),
 "cited_experiment_ids": ["E0023-lcb-ceiling","E0024-lcb-governor"],
 "withdrawn_ids": ["E0019-predictor-loss-math","E0017-soft-governor-math"],
}
traps = run_trap_checks(ev_dict)
red = [n for n,(ok,_) in traps.items() if not ok]
verdict = "INCONCLUSIVE" if (lo<0<hi or not red) else "BLOCKED"
if lo > 0: verdict = "PASS"
if red: verdict = "BLOCKED"
print(render(traps))

spec = ExperimentSpec(
    exp_id="E0026-execution-feedback",
    title="Execution feedback from public tests as an allocation signal",
    model="Gemini-Pro-1.5 (May) generations, published by LiveCodeBench",
    budget={"axis":"samples k in 1..10, sequential with early stop",
            "B_star": float(C.mean()),
            "charged":"exact tokenizer count over published generations",
            "execution_cost_s": float(np.sum([r["exec_latency_s"] for r in rows]))},
    seeds={"split":"sha256(question_id) parity","bootstrap":0},
    split={"calibration":len(cal),"evaluation":len(ev)},
    metric="pass-within-k at matched realised inference cost; primary = Governor "
           "minus the randomised fixed envelope at the Governor's own cost",
    params={"features":list(F),"tau":float(tau),
            "permitted_feature_set":list(FEATURE_NAMES)},
    notes="Execution feedback GENERATED by running each candidate against "
          "public_test_cases in a sandbox. LiveCodeBench's published metadata was "
          "forbidden: its emptiness is exactly the label (1530 empty/PASS, 2470 "
          "non-empty/FAIL, zero off-diagonal). private_test_cases never read.")
run = ExperimentRun(spec, overwrite=True)
for i,q in enumerate(ev):
    run.append({"qid":q,"gov_k":int(K[i]),"gov_pass":int(U[i]),
                "fixed_matched":float(Ub[i]),"tokens":float(C[i])})
run.finalize(
  summary={"governor_U":float(U.mean()),"fixed_matched":float(ub),"oracle":float(oracle),
           "sequential_ceiling":float(oracle-ub),
           "primary_mean":float(U.mean()-ub),"primary_lo":float(lo),"primary_hi":float(hi),
           "governor_tokens":float(C.mean()),"k10_tokens":float(k10),
           "cost_saving_vs_k10":float(C.mean()/k10-1),
           "predictor_auc_hopeless":0.819,"predictor_auc_this_sample":0.853,
           "predictor_auc_later_sample":0.661,
           "headroom_captured":float((U.mean()-ub)/(oracle-ub)) if oracle>ub else 0.0,
           "tau":float(tau),"verdict":"INCONCLUSIVE"},
  metrics={"tau":float(tau)}, traps=traps, verdict=verdict)
print(f"\n  recorded: experiments/E0026-execution-feedback/  verdict={verdict}")
print(f"  advantage {U.mean()-ub:+.4f} [{lo:+.4f},{hi:+.4f}]  cost {C.mean():.1f} ({C.mean()/k10-1:+.1%} vs k=10)")
