"""Labelled checkpoint corpus, collected under a randomised behaviour policy.

Decision Record section G.1 — the load-bearing decision of revision 2.

A corpus generated by a single fixed policy has no action overlap: in any given
state you only ever observe the action that policy chose, so the outcome of every
*other* action is unidentifiable and no amount of regularisation recovers it. That
holds whether you fit Q(s,a) directly or compose V with an effect model, so it is
not a question the D1 experiment can answer -- it has to be fixed at collection
time.

Collecting with an epsilon-greedy behaviour policy restores overlap, and the
randomised subset is unconfounded by construction: on those decisions the action was
chosen independently of the state, so the observed outcome difference is causal.

Each decision becomes one checkpoint, labelled with the *eventual* outcome of the
episode it belongs to. That label is constant within an episode, which has a
consequence for sample size that section J.8's gate has to take seriously -- see
`governor/corpus/gate.py`.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from pathlib import Path

from governor.accounting.meter import Envelope
from governor.arms.baselines import EpsilonGreedyCollector, HeuristicArm
from governor.cognitive.belief import Channel
from governor.envs.families import Family
from governor.models.cost import CostProfile
from governor.policy.runner import (
    EpisodeContext,
    config_hash,
    deterministic_candidates,
    propose,
    run_episode,
)
from governor.envs.synthbug import Action, Tier

CORPUS_SCHEMA = """
CREATE TABLE IF NOT EXISTS checkpoints (
    episode_id   TEXT NOT NULL,
    decision_id  INTEGER NOT NULL,
    family       TEXT NOT NULL,
    split        TEXT NOT NULL,
    seed         INTEGER NOT NULL,
    action       TEXT NOT NULL,
    mode         TEXT NOT NULL,
    tier         TEXT NOT NULL,
    was_random   INTEGER NOT NULL,
    n_admissible INTEGER NOT NULL,
    features     TEXT NOT NULL,
    label        INTEGER NOT NULL,
    PRIMARY KEY (episode_id, decision_id)
);
CREATE INDEX IF NOT EXISTS idx_ckpt_family ON checkpoints(family, split);
CREATE INDEX IF NOT EXISTS idx_ckpt_action ON checkpoints(mode, tier);
CREATE INDEX IF NOT EXISTS idx_ckpt_random ON checkpoints(was_random);
"""


@dataclass(slots=True)
class Checkpoint:
    """One decision, labelled by the eventual fate of its episode."""

    episode_id: str
    decision_id: int
    family: str
    split: str
    seed: int
    action: str
    mode: str
    tier: str
    was_random: bool
    n_admissible: int
    features: dict[str, float]
    label: int  # 1 if the episode eventually succeeded


@dataclass(slots=True)
class RecordingCollector:
    """Wraps the epsilon-greedy collector and captures every decision.

    The runner writes decision records to SQLite, but the corpus needs the feature
    vector *as the policy saw it* plus the action actually taken, keyed so it can be
    joined to the episode's eventual outcome. Capturing it here keeps the runner
    free of corpus-specific concerns.
    """

    inner: EpsilonGreedyCollector
    rows: list[dict] = field(default_factory=list)
    name: str = "collector"

    def __post_init__(self) -> None:
        self.name = self.inner.name

    @property
    def epsilon(self) -> float:
        return self.inner.epsilon

    def reset(self, task) -> None:  # noqa: ANN001
        self.inner.reset(task)

    def propose(self, ctx: EpisodeContext):  # noqa: ANN201
        return propose(self.inner, ctx)

    def act(self, ctx: EpisodeContext, admissible: list[Action]):  # noqa: ANN201
        action, reason = self.inner.act(ctx, admissible)
        self.rows.append(
            {
                "features": ctx.features(),
                "action": str(action),
                "mode": str(action.mode),
                "tier": str(action.tier),
                "was_random": reason == "EXPLORATION_RANDOM",
                "n_admissible": len(admissible),
            }
        )
        return action, reason

    def drain(self) -> list[dict]:
        out, self.rows = self.rows, []
        return out


def build_corpus(
    *,
    families: list[Family],
    heldout: list[Family],
    episodes_per_family: int,
    profile: CostProfile,
    channels: dict[Tier, Channel],
    envelope: Envelope,
    epsilon: float = 0.30,
    seed0: int = 0,
) -> list[Checkpoint]:
    """Run episodes under epsilon-greedy and emit labelled checkpoints."""
    out: list[Checkpoint] = []
    cfg_h = config_hash(envelope, epsilon)

    for split, group in (("train", families), ("heldout", heldout)):
        for fam in group:
            collector = RecordingCollector(
                EpsilonGreedyCollector(base=HeuristicArm(), epsilon=epsilon, seed=seed0)
            )
            for i in range(episodes_per_family):
                seed = seed0 + i
                task = fam.task(seed)
                eid = f"{fam.name}|{seed}"
                result = run_episode(
                    task=task,
                    arm=collector,
                    envelope=envelope,
                    profile=profile,
                    channel_for=channels,
                    store=None,
                    episode_id=eid,
                    cfg_hash=cfg_h,
                )
                label = int(result.succeeded)
                for j, row in enumerate(collector.drain()):
                    out.append(
                        Checkpoint(
                            episode_id=eid,
                            decision_id=j,
                            family=fam.name,
                            split=split,
                            seed=seed,
                            label=label,
                            **row,
                        )
                    )
    return out


def write_corpus(checkpoints: list[Checkpoint], path: str | Path) -> None:
    import sqlite3

    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(p)
    conn.executescript(CORPUS_SCHEMA)
    conn.executemany(
        """INSERT OR REPLACE INTO checkpoints VALUES
           (:episode_id,:decision_id,:family,:split,:seed,:action,:mode,:tier,
            :was_random,:n_admissible,:features,:label)""",
        [
            {**asdict(c), "features": json.dumps(c.features), "was_random": int(c.was_random)}
            for c in checkpoints
        ],
    )
    conn.commit()
    conn.close()


def feature_names(checkpoints: list[Checkpoint]) -> list[str]:
    return sorted(checkpoints[0].features) if checkpoints else []
